"""PrivateBin uploader for sharing full transcripts."""

import os
from typing import Optional

import privatebinapi


def format_transcript_for_readability(
    transcription: str,
    title: str,
    webpage_url: str
) -> str:
    """
    Format raw transcript for readability.

    Cleans up formatting and adds metadata without changing content/language.

    Args:
        transcription: Raw transcription text
        title: Video title
        webpage_url: Source URL

    Returns:
        Formatted transcript text
    """
    # Add header with metadata
    formatted = f"""# Full Transcript: {title}

**Source:** {webpage_url}
**Generated by:** yt-transcribe

---

"""

    # Clean up the transcription
    lines = transcription.split('\n')
    cleaned_lines = []

    for line in lines:
        line = line.strip()
        if not line:
            # Preserve paragraph breaks
            if cleaned_lines and cleaned_lines[-1] != '':
                cleaned_lines.append('')
            continue

        # Add the line
        cleaned_lines.append(line)

    # Join lines with proper spacing
    formatted += '\n'.join(cleaned_lines)

    return formatted


def upload_to_privatebin(
    content: str,
    expiration: str = "1week",
    burn_after_reading: bool = False,
    server_url: Optional[str] = None
) -> dict:
    """
    Upload content to PrivateBin and return the URL.

    Args:
        content: Text content to upload
        expiration: Expiration time (5min, 10min, 1hour, 1day, 1week, 1month, 1year, never)
        burn_after_reading: If True, paste is deleted after first read
        server_url: PrivateBin server URL (defaults to PRIVATEBIN_SERVER env var or vim.cx)

    Returns:
        Dict with keys: full_url, id, passcode, deletetoken

    Raises:
        RuntimeError: If upload fails
    """
    # Get server URL
    if server_url is None:
        server_url = os.getenv("PRIVATEBIN_SERVER", "https://privatebin.net")

    try:
        response = privatebinapi.send(
            server_url,
            text=content,
            expiration=expiration,
            burn_after_reading=burn_after_reading
        )

        if response.get("status") != 0:
            raise RuntimeError(f"PrivateBin upload failed with status: {response.get('status')}")

        return {
            "full_url": response["full_url"],
            "id": response["id"],
            "passcode": response.get("passcode", ""),
            "deletetoken": response.get("deletetoken", "")
        }

    except Exception as e:
        raise RuntimeError(f"Failed to upload to PrivateBin: {e}") from e


def upload_transcript(
    transcription: str,
    title: str,
    webpage_url: str,
    expiration: str = "1week"
) -> str:
    """
    Format and upload full transcript to PrivateBin.

    Args:
        transcription: Raw transcription text
        title: Video title
        webpage_url: Source URL
        expiration: How long to keep the paste (default: 1week)

    Returns:
        Full URL to the uploaded transcript

    Raises:
        RuntimeError: If upload fails
    """
    # Format the transcript
    formatted = format_transcript_for_readability(transcription, title, webpage_url)

    # Upload to PrivateBin
    result = upload_to_privatebin(formatted, expiration=expiration)

    return result["full_url"]
